### ISSUE TITLE
Improve documentation website

### ISSUE THREAD

**Issue by agdimech** [awslabs/nx-plugin-for-aws#18]
The documentation site is quite bare bones and needs to be improved.
```[tasklist]
### Tasks
- [ ] Primer for NX (including how caching works, NX plugin for supported IDEs, nx graph, etc)
- [ ] Upgrade/migration process
- [ ] Polyglot packages i.e: Python + TS
- [ ] Single version policy i.e: https://nx.dev/concepts/decisions/dependency-management
- [ ] Add examples for each of the generators
- [ ] FAQ
- [ ] Prerequisites and Installation instructions
- [ ] Document tsreferences/path for TS projects (no need to explicitly declare deps, nx sync, etc)
- [ ] Document VSCode tips i.e: useful plugins, workspaces, etc
- [ ] How to add @aws/nx-plugin to existing project
- [ ] nx watch i.e # in watch mode nx watch --includeDependentProjects --projects=<app-name> -- nx run <app-name>:deploy:quick
- [ ] update root README
```
