### ISSUE TITLE
Create API Connection

### ISSUE THREAD

**Issue by agdimech** [awslabs/nx-plugin-for-aws#19]
Add the generator for the API Connection.

```[tasklist]
### Tasks
- [x] API connection generator
- [x] Vanilla TS client
- [x] Streaming support (TS)
- [ ] React hooks/query
- [ ] Python vanilla client
- [ ] Python streaming support
- [x] Unit testing
- [x] Update Smoke tests
- [x] Add README.md with details on how to use the API Connection
- [x] Update documentation site to include description, examples, etc
```
