### ISSUE TITLE
Make repository public

### ISSUE THREAD

**Issue by agdimech** [awslabs/nx-plugin-for-aws#23]
Flip the switch to make this repository public and cross-reference from PDK repository.
```[tasklist]
### Tasks
- [ ] Make repository public
- [ ] Update @aws/pdk to reference this repository for non-projen based solution
- [ ] LaunchManager setup
- [ ] List plugin on nx registry https://nx.dev/extending-nx/recipes/publish-plugin#list-your-nx-plugin
```
