### ISSUE TITLE
Python project support

### ISSUE THREAD

**Issue by agdimech** [awslabs/nx-plugin-for-aws#28]
We need to add a new generator for creating a Python project (lib and app).

The project should achieve the following:

- linting
- unit test support
- bundling
- shared venv

A simple solution could be: https://docs.astral.sh/uv/concepts/projects/workspaces/#getting-started
```[tasklist]
### Tasks
- [x] Create generator with options for app/lib
- [x] Create generator for Py Infra
- [x] Add lint/format task
- [x] Add test task with stubbed tests
- [x] Support for workspaces and isolated
- [x] Documentation (Py generator specific)
- [x] Documentation (polyglot ts + py)
- [x] E2E tests
```
